
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
   # Robot Configuration Parameters
   max_vel_x: 0.1 #x方向，机器人最大线速度，单位是m/s
   min_vel_x:  0.02 #x方向，机器人最小线速度，单位是m/s
   max_vel_y: 0.0
   min_vel_y:  0.0
   max_vel_theta:  0.15 #机器人最大转动速度，单位是rad/s, 0.15--8.6度/s
   min_vel_theta: -0.15
   min_in_place_vel_theta: 0.1  #机器人最小原地旋转速度，单位rad/s

   escape_vel: -0.1 #机器人的逃离速度，即背向相反方向行走速度，单位是m/s

   acc_lim_x: 0.1 #在x方向上最大的线加速度，单位是m/s^2
   acc_lim_y: 0.0
   acc_lim_theta: 0.05 #最大角加速度，单位是rad/s^2

   xy_goal_tolerance: 0.2 # 10 cm  表示接近目标允许的误差（m），值不能小于地图的分辨率
   yaw_goal_tolerance: 0.2 # about 12 degrees ，接近目标方向（就弧度来说）允许的误差（rad），此值太小会造成机器人在目标附近震荡
   latch_xy_goal_tolerance: false

   holonomic_robot: false #除非拥有一个全方位的机器人，否则设置为false

   sim_time: 2.0 #规划器能看到未来多少秒
   sim_granularity: 0.05
   angular_sim_granularity: 0.025
   vx_samples: 10
   vtheta_samples: 20
   controller_frequency: 10

   meter_scoring: true  #gdist_scale和pdist_scale参数是否假设goal_distance和path_distance以米或者单元来表达
   pdist_scale: 0.8 #紧贴全局路径比到达目标的相对重要性，如果此值比gdist_scale大，那么机器人会更紧靠全局路径行走
   gdist_scale: 0.6 #到达目标比紧靠全局路径的相对重要性，如果此值比pdist_scale大，那么机器人会采取任意路径优先到达目标
   occdist_scale: 0.1
   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   dwa: true   #当模拟轨迹走向未来，是否使用动态窗口法
   publish_cost_grid_pc: true

   oscillation_reset_dist: 0.4
   forward_point_distance: 0.4
