global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   static_map: true
#   rolling_window: false      #滚动窗口
   resolution: 0.05
   transform_tolerance: 1.5
#   map_type: costmap
   plugins:
      - {name: static_layer, type: "costmap_2d::StaticLayer"}
      - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
      - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
