shutdown_costmaps: false

controller_frequency: 10.0
controller_patience: 15.0 #1.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

# default: trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"

# navfn/NavfnROS、global_planner/GlobalPlanner、carrot_planner/CarrotPlanner三种；
base_global_planner: "navfn/NavfnROS"

recovery_behavior_enabled: true
recovery_behaviors: [{"name":"super_conservative_reset1", "type":"clear_costmap_recovery/ClearCostmapRecovery"}]
reset_distance: 5.0
